<?xml version="1.0"?>
<doc>
<assembly>
<name>
eZRevtiTools
</name>
</assembly>
<members>
<member name="M:eZRevtiTools.ExtensionMethods.Element(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Document)">
	<summary> 从ElementId返回其所在的Document中的Element对象 </summary>
	<param name="elementId"></param>
	<param name="Doc">此elementId所位于的文档</param>
</member><member name="M:eZRevtiTools.ExtensionMethods.FindFamily(Autodesk.Revit.DB.Document,System.String)">
	<summary> 返回项目文档中指定名称的族Family对象 </summary>
	<param name="FamilyName">在此文档中，所要搜索的族对象的名称</param>
</member><member name="M:eZRevtiTools.ExtensionMethods.Instances(Autodesk.Revit.DB.Family)">
	<summary> 返回项目文档中某族Family的所有实例 </summary>
	<param name="Family"></param>
</member><member name="M:eZRevtiTools.ExtensionMethods.Instances(Autodesk.Revit.DB.FamilySymbol)">
	<summary> 返回项目文档中某族类型FamilySymbol的所有实例 </summary>
	<param name="FamilySymbol"></param>
</member><member name="M:eZRevtiTools.ExtensionMethods.ToString_Matrix(Autodesk.Revit.DB.Transform)">
	<summary> 以矩阵的形式返回变换矩阵，仅作显示之用 </summary>
	<param name="Trans"></param>
</member><member name="M:eZRevtiTools.ExtensionMethods.Foot2mm(System.Double)">
	<summary> 长度单位转换：将英尺转换为毫米 1英尺=304.8mm </summary>
	<param name="value_foot"></param>
	<remarks> 1 foot = 12 inches = 304.8 mm</remarks>
</member><member name="T:eZRevtiTools.ExtensionMethods">
	<summary>
 Revit中对象的扩展方法
 </summary>
	<remarks></remarks>
</member><member name="P:eZRevtiTools.My.Resources.Resources.ResourceManager">
	<summary>
  Returns the cached ResourceManager instance used by this class.
</summary>
</member><member name="P:eZRevtiTools.My.Resources.Resources.Culture">
	<summary>
  Overrides the current thread's CurrentUICulture property for all
  resource lookups using this strongly typed resource class.
</summary>
</member><member name="T:eZRevtiTools.My.Resources.Resources">
	<summary>
  A strongly-typed resource class, for looking up localized strings, etc.
</summary>
</member><member name="M:eZRevtiTools.Test_Addin.ExternalApplication.NewRibbon(Autodesk.Revit.UI.UIControlledApplication)">
	<summary>
 创建一个新的 Ribbon
 </summary>
</member><member name="M:eZRevtiTools.rvtTools.GetWarningValue(System.String)">
	<summary>
 提取WarningValueUsing.dat中的WarningValue类
 </summary>
	<param name="FullPath">WarningValueUsing.dat的绝对路径</param>
</member><member name="T:eZRevtiTools.rvtTools">
	<summary>
	</summary>
	<remarks></remarks>
</member><member name="M:eZRevtiTools.ExamplesCodes.GetGeometry">
	<summary>
 返回Element的几何数据
 </summary>
	<remarks></remarks>
</member><member name="M:eZRevtiTools.ExamplesCodes.FindSupporting">
	<summary> 射线法：找到与梁相交的所有墙对象 </summary>
</member><member name="M:eZRevtiTools.ExamplesCodes.FindIntersectWallsByElement">
	<summary> 找到与某Element的几何实体相交的Elements </summary>
</member><member name="M:eZRevtiTools.ExamplesCodes.FindIntersectWallsByGeometry">
	<summary>ElementIntersectsSolidFilter: 找到与某Solid相交的Elements </summary>
</member><member name="M:eZRevtiTools.ExamplesCodes.ElementParameterFilter_FindOjbectsInSpecificRoom(Autodesk.Revit.UI.ExternalCommandData)">
	<summary>
 ElementParameterFilter 参数过滤器：找到一个房间内的所有对象
 </summary>
	<remarks>提示: 参数过滤条件可能比其他的类型过滤条件要快，但是这要视条件而定。毕竟这是一个慢过，使用时请按照过滤标准的复杂程度而异。</remarks>
</member><member name="M:eZRevtiTools.ExamplesCodes.ElementParameterFilter_FindRooms(Autodesk.Revit.DB.Document)">
	<summary>
 ElementParameterFilter参数过滤器 Creates an ElementParameter filter to find rooms whose area is greater than specified value
 </summary>
	<remarks>提示: 参数过滤条件可能比其他的类型过滤条件要快，但是这要视条件而定。毕竟这是一个慢过，使用时请按照过滤标准的复杂程度而异。</remarks>
</member><member name="T:eZRevtiTools.ExamplesCodes">
	<summary>
 一些效果实现的示例代码
 </summary>
	<remarks></remarks>
</member>
</members>
</doc>